from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QRegularExpression
from my_lib.converter import *


class Ui_Converter_ui(object):
    def setupUi(self, Converter_ui):
        Converter_ui.setObjectName("Converter_ui")
        Converter_ui.resize(340, 340)
        Converter_ui.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Converter_ui)
        self.centralwidget.setStyleSheet("background-color: #8D77FE;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.USD_input = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.USD_input.sizePolicy().hasHeightForWidth())
        self.USD_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.USD_input.setFont(font)
        self.USD_input.setStyleSheet("border-radius: 5px; background-color: #FEFEFF; color: #686868 ")
        self.USD_input.setMaxLength(18)
        self.USD_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.USD_input.setObjectName("USD_input")
        self.verticalLayout.addWidget(self.USD_input)
        self.RUB_input = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RUB_input.sizePolicy().hasHeightForWidth())
        self.RUB_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.RUB_input.setFont(font)
        self.RUB_input.setStyleSheet("border-radius: 5px; background-color: #FEFEFF; color: #686868 ")
        self.RUB_input.setMaxLength(18)
        self.RUB_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.RUB_input.setObjectName("RUB_input")
        self.verticalLayout.addWidget(self.RUB_input)
        self.KZT_input = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.KZT_input.sizePolicy().hasHeightForWidth())
        self.KZT_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.KZT_input.setFont(font)
        self.KZT_input.setStyleSheet("border-radius: 5px; background-color: #FEFEFF; color: #686868 ")
        self.KZT_input.setMaxLength(18)
        self.KZT_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.KZT_input.setObjectName("KZT_input")
        self.verticalLayout.addWidget(self.KZT_input)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 1)
        Converter_ui.setCentralWidget(self.centralwidget)

        self.retranslateUi(Converter_ui)
        QtCore.QMetaObject.connectSlotsByName(Converter_ui)

    def retranslateUi(self, Converter_ui):
        _translate = QtCore.QCoreApplication.translate
        Converter_ui.setWindowTitle(_translate("Converter_ui", "Converter"))
        self.USD_input.setPlaceholderText(_translate("Converter_ui", "USD"))
        self.RUB_input.setPlaceholderText(_translate("Converter_ui", "RUB"))
        self.KZT_input.setPlaceholderText(_translate("Converter_ui", "KZT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Converter_ui = QtWidgets.QMainWindow()
    ui = Ui_Converter_ui()
    ui.setupUi(Converter_ui)
    Converter_ui.show()
    sys.exit(app.exec())
